version: "3.8"

services: 
  web:
    stdin_open: true
    build: .
    ports: 
      - "3000:3000"
  
  server:
    build: ./json-server
    ports: 
      - "3001:3001"
    volumes:
      - ./json-server/data:/app/data